<?php

/**
 * BlastResponse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    makeaminyan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BlastResponse extends BaseBlastResponse {

    public function getUser() {
        return Doctrine::getTable('SfGuardUser')->find($this->getUserId());
    }

    public function getFootprint() {
        return $this->getAdditional() + 1;
    }
}
