<?php

/**
 * BlastResponseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlastResponseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlastResponseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlastResponse');
    }
}