<?php

/**
 * MinyanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MinyanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MinyanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Minyan');
    }
}