<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable {

    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public function emailExists($email) {
        if (!$email)
            return false;
        $email = $this->findOneByUsername($email);

        if ($email)
            return true;
        return false;
    }

    public function phoneExists($phone) {
        if (!$phone)
            return false;
        $phone = $this->findOneByPhone(sfValidatorPhoneNumber::cleanProcess($phone));

        if ($phone)
            return true;
        return false;
    }

}