<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('minyan', 'identifier', 'string', '100', array(
             'notnull' => '',
             ));
        $this->addColumn('minyan', 'address1', 'string', '255', array(
             'notnull' => '',
             ));
        $this->addColumn('minyan', 'address2', 'string', '255', array(
             'notnull' => '',
             ));
        $this->addColumn('minyan', 'city', 'string', '255', array(
             'notnull' => '',
             ));
        $this->addColumn('minyan', 'state', 'string', '2', array(
             'notnull' => '',
             ));
        $this->addColumn('minyan', 'zip', 'string', '10', array(
             'notnull' => '',
             ));
        $this->addColumn('minyan', 'country', 'string', '255', array(
             'notnull' => '',
             'default' => 'United States',
             ));
    }

    public function down()
    {
        $this->removeColumn('minyan', 'identifier');
        $this->removeColumn('minyan', 'address1');
        $this->removeColumn('minyan', 'address2');
        $this->removeColumn('minyan', 'city');
        $this->removeColumn('minyan', 'state');
        $this->removeColumn('minyan', 'zip');
        $this->removeColumn('minyan', 'country');
    }
}