<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('blast', 'number_phone_calls', 'integer', '4', array(
             'notnull' => '1',
             ));
        $this->addColumn('blast', 'number_texts', 'integer', '4', array(
             'notnull' => '1',
             ));
        $this->addColumn('blast', 'number_emails', 'integer', '4', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('blast', 'number_phone_calls');
        $this->removeColumn('blast', 'number_texts');
        $this->removeColumn('blast', 'number_emails');
    }
}